apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cfi-platform-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/yusufcalisir/CF-Intelligence.git'
    targetRevision: HEAD
    path: deployments/helm/cfi-platform-root
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cfi-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
