global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'log-receiver'

receivers:
  - name: 'log-receiver'
    webhook_configs:
      - url: 'http://gateway:8000/api/v1/monitoring/alerts/webhook'
        send_resolved: true
