"""Phase 2 domain entities.

Core business objects for the AML intelligence platform.
These extend the Phase 1 entities with alert management, case
investigations, entity resolution, and shared intelligence concepts.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone

from app.domain.enums import (
    AlertSeverity,
    AlertStatus,
    CasePriority,
    CaseStatus,
    EntityType,
    IntelligenceType,
    RelationshipType,
    RiskLevel,
    ScenarioType,
)


@dataclass
class Alert:
    """A fraud alert generated by a bank's detection pipeline.

    Alerts are the primary output of the risk engine. They never contain
    raw transaction data — only risk scores, reason codes, and
    privacy-preserving entity identifiers.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    bank_id: str = ""
    transaction_id: str = ""
    risk_score: float = 0.0
    severity: AlertSeverity = AlertSeverity.MEDIUM
    status: AlertStatus = AlertStatus.NEW
    reason_codes: list[str] = field(default_factory=list)
    confidence: float = 0.0
    involved_entity_ids: list[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime | None = None

    # Explainability
    top_features: list[dict[str, float | str]] = field(default_factory=list)
    risk_factors: list[str] = field(default_factory=list)
    model_confidence: float = 0.0
    historical_evidence: list[str] = field(default_factory=list)

    @property
    def is_actionable(self) -> bool:
        """Whether this alert requires investigation."""
        return self.severity in (AlertSeverity.CRITICAL, AlertSeverity.HIGH)


@dataclass
class Case:
    """An investigation case linking multiple alerts.

    Cases track the investigation lifecycle from initial detection
    through resolution. They aggregate evidence from multiple alerts
    and support collaborative investigation workflows.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    title: str = ""
    status: CaseStatus = CaseStatus.OPEN
    priority: CasePriority = CasePriority.P3_MEDIUM
    assigned_to: str | None = None
    alert_ids: list[str] = field(default_factory=list)
    notes: list[CaseNote] = field(default_factory=list)
    timeline: list[CaseEvent] = field(default_factory=list)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime | None = None
    closed_at: datetime | None = None
    total_risk_score: float = 0.0

    @property
    def is_open(self) -> bool:
        return self.status not in (
            CaseStatus.CLOSED_CONFIRMED,
            CaseStatus.CLOSED_FALSE_POSITIVE,
        )

    @property
    def duration_hours(self) -> float | None:
        end = self.closed_at or datetime.now(timezone.utc)
        return (end - self.created_at).total_seconds() / 3600


@dataclass
class CaseNote:
    """An investigation note attached to a case."""

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    case_id: str = ""
    author: str = "analyst"
    content: str = ""
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class CaseEvent:
    """A timestamped event in a case's investigation timeline."""

    event_type: str = ""  # "created", "status_changed", "note_added", "alert_linked"
    description: str = ""
    actor: str = "system"
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: dict = field(default_factory=dict)


@dataclass
class Entity:
    """A privacy-preserving entity in the financial crime graph.

    Entities represent real-world objects (customers, merchants, devices, etc.)
    identified by deterministic hashes rather than raw PII. This enables
    cross-institution entity matching without exposing private information.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    entity_type: EntityType = EntityType.CUSTOMER
    privacy_id: str = ""  # HMAC-SHA256 hash of the raw identifier
    bank_id: str = ""
    display_label: str = ""  # e.g. "CUST-a3f2", "MERCH-8b1c" (non-PII)
    attributes: dict = field(default_factory=dict)  # Non-sensitive metadata
    risk_level: RiskLevel = RiskLevel.MINIMAL
    alert_count: int = 0
    first_seen: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    last_seen: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class Relationship:
    """An edge in the entity relationship graph.

    Represents a known connection between two entities with a confidence
    score and supporting evidence.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    source_entity_id: str = ""
    target_entity_id: str = ""
    relationship_type: RelationshipType = RelationshipType.OWNS
    confidence: float = 1.0
    evidence: list[str] = field(default_factory=list)  # Alert IDs, transaction hashes
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass
class SharedIntelligence:
    """Cross-institution intelligence published to the shared layer.

    This is what banks share with each other — never raw transactions.
    It contains only hashed identifiers, risk indicators, and pattern
    descriptions that other institutions can correlate against their
    own data.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    source_bank_id: str = ""
    intelligence_type: IntelligenceType = IntelligenceType.FRAUD_ALERT
    privacy_hash: str = ""  # Hashed entity identifier
    risk_indicator: float = 0.0
    description: str = ""
    entity_type: EntityType | None = None
    related_alert_count: int = 0
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    expires_at: datetime | None = None


@dataclass
class StreamingEvent:
    """A real-time event for WebSocket streaming.

    Used during scenario replay to simulate live transaction monitoring.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    event_type: str = ""  # "transaction", "alert", "intelligence", "entity_resolved"
    bank_id: str = ""
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    payload: dict = field(default_factory=dict)
    delay_ms: int = 0  # Delay before this event fires (for scenario pacing)


@dataclass
class Scenario:
    """A pre-built fraud scenario for simulation.

    Scenarios generate a scripted sequence of events that demonstrate
    how collaborative intelligence improves detection. Each scenario
    involves multiple banks observing fragments of the same fraud.
    """

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    scenario_type: ScenarioType = ScenarioType.FRAUD_RING
    name: str = ""
    description: str = ""
    banks_involved: list[str] = field(default_factory=list)
    events: list[StreamingEvent] = field(default_factory=list)
    duration_seconds: float = 0.0
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
