import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useAlerts, useAlertExplainability } from '../api/queries';
import { BANK_NAMES, SEVERITY_COLORS } from '../api/types';
import type { Alert } from '../api/types';

const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low', 'info'];

export default function AlertsPage() {
  const [selectedBank, setSelectedBank] = useState<string>('');
  const [selectedSeverity, setSelectedSeverity] = useState<string>('');
  const [selectedAlert, setSelectedAlert] = useState<Alert | null>(null);

  const { data: alerts, isLoading } = useAlerts({
    bank_id: selectedBank || undefined,
    severity: selectedSeverity || undefined,
  });

  return (
    <div className="space-y-6">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <h1 className="text-2xl font-bold gradient-text mb-1">
          Alert Intelligence
        </h1>
        <p className="text-sm text-[var(--color-text-muted)] max-w-2xl">
          Privacy-preserving fraud alerts generated by the risk scoring engine.
          Each alert contains only risk indicators and hashed identifiers — never raw transaction data.
        </p>
      </motion.div>

      {/* Filters */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex gap-3 flex-wrap"
      >
        <select
          value={selectedBank}
          onChange={(e) => setSelectedBank(e.target.value)}
          className="glass-card px-3 py-2 text-sm rounded-lg bg-transparent border border-[var(--color-border)] text-[var(--color-text)]"
        >
          <option value="">All Banks</option>
          {Object.entries(BANK_NAMES).map(([id, name]) => (
            <option key={id} value={id}>{name}</option>
          ))}
        </select>

        <select
          value={selectedSeverity}
          onChange={(e) => setSelectedSeverity(e.target.value)}
          className="glass-card px-3 py-2 text-sm rounded-lg bg-transparent border border-[var(--color-border)] text-[var(--color-text)]"
        >
          <option value="">All Severities</option>
          {SEVERITY_ORDER.map((s) => (
            <option key={s} value={s}>{s.charAt(0).toUpperCase() + s.slice(1)}</option>
          ))}
        </select>

        <div className="ml-auto text-sm text-[var(--color-text-muted)] self-center">
          {alerts?.length ?? 0} alerts
        </div>
      </motion.div>

      {/* Alert List + Detail */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Alert Feed */}
        <div className="lg:col-span-2 space-y-3">
          {isLoading ? (
            <div className="glass-card p-8 text-center text-[var(--color-text-muted)]">
              Loading alerts...
            </div>
          ) : !alerts?.length ? (
            <div className="glass-card p-8 text-center text-[var(--color-text-muted)]">
              <p className="text-lg mb-2">No alerts yet</p>
              <p className="text-sm">Run a scenario from the Scenarios page to generate alerts.</p>
            </div>
          ) : (
            <AnimatePresence>
              {alerts.map((alert, i) => (
                <AlertCard
                  key={alert.id}
                  alert={alert}
                  index={i}
                  isSelected={selectedAlert?.id === alert.id}
                  onClick={() => setSelectedAlert(alert)}
                />
              ))}
            </AnimatePresence>
          )}
        </div>

        {/* Explainability Panel (Desktop) */}
        <div className="hidden lg:block lg:col-span-1">
          {selectedAlert ? (
            <ExplainabilityPanel alert={selectedAlert} />
          ) : (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="glass-card p-6 text-center text-[var(--color-text-muted)] sticky top-6"
            >
              <div className="text-3xl mb-3">🔍</div>
              <p>Select an alert to view its explainability report</p>
            </motion.div>
          )}
        </div>
      </div>

      {/* Mobile Explainability Modal */}
      {selectedAlert && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm lg:hidden">
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            className="glass-card w-full max-w-lg max-h-[85vh] overflow-y-auto relative flex flex-col p-0"
          >
            <div className="p-4 border-b border-[var(--color-border)] flex items-center justify-between sticky top-0 bg-[var(--color-bg-card)] z-10">
              <h3 className="font-bold text-[var(--color-text-primary)]">Alert Details</h3>
              <button
                onClick={() => setSelectedAlert(null)}
                className="p-1 rounded-md text-[var(--color-text-muted)] hover:text-[var(--color-text-primary)] hover:bg-[var(--color-bg-card-hover)] focus:outline-none"
                aria-label="Close details"
              >
                <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <div className="p-5 overflow-y-auto">
              <ExplainabilityPanel alert={selectedAlert} />
            </div>
          </motion.div>
        </div>
      )}
    </div>
  );
}

function AlertCard({
  alert,
  index,
  isSelected,
  onClick,
}: {
  alert: Alert;
  index: number;
  isSelected: boolean;
  onClick: () => void;
}) {
  const severityColor = SEVERITY_COLORS[alert.severity] || '#6b7280';

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      transition={{ delay: index * 0.05 }}
      onClick={onClick}
      className={`glass-card p-4 cursor-pointer transition-all duration-200 hover:scale-[1.01] ${
        isSelected ? 'ring-2 ring-[var(--color-primary)]' : ''
      }`}
    >
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center gap-2">
          <span
            className="px-2 py-0.5 rounded-full text-xs font-bold uppercase text-white"
            style={{ backgroundColor: severityColor }}
          >
            {alert.severity}
          </span>
          <span className="text-xs text-[var(--color-text-muted)]">
            {BANK_NAMES[alert.bank_id] || alert.bank_id}
          </span>
        </div>
        <span className="text-xs text-[var(--color-text-muted)]">
          {new Date(alert.created_at).toLocaleTimeString()}
        </span>
      </div>

      <div className="flex items-center gap-4 mb-2">
        <div>
          <div className="text-2xl font-bold" style={{ color: severityColor }}>
            {alert.risk_score.toFixed(0)}
          </div>
          <div className="text-[10px] uppercase text-[var(--color-text-muted)]">Risk Score</div>
        </div>
        <div className="flex-1">
          <div className="h-2 bg-[var(--color-surface-alt)] rounded-full overflow-hidden">
            <motion.div
              initial={{ width: 0 }}
              animate={{ width: `${alert.risk_score / 10}%` }}
              transition={{ delay: index * 0.05 + 0.2, duration: 0.5 }}
              className="h-full rounded-full"
              style={{ backgroundColor: severityColor }}
            />
          </div>
        </div>
        <div className="text-right">
          <div className="text-sm font-mono">{(alert.confidence * 100).toFixed(1)}%</div>
          <div className="text-[10px] uppercase text-[var(--color-text-muted)]">Confidence</div>
        </div>
      </div>

      <div className="flex flex-wrap gap-1">
        {alert.reason_codes.map((code) => (
          <span
            key={code}
            className="px-1.5 py-0.5 text-[10px] font-mono rounded bg-[var(--color-surface-alt)] text-[var(--color-text-muted)]"
          >
            {code}
          </span>
        ))}
      </div>
    </motion.div>
  );
}

function ExplainabilityPanel({ alert }: { alert: Alert }) {
  const { data: report, isLoading } = useAlertExplainability(alert.id);

  return (
    <motion.div
      key={alert.id}
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="glass-card p-5 sticky top-6 space-y-4"
    >
      <h3 className="text-sm font-bold uppercase text-[var(--color-text-muted)]">
        Explainability Report
      </h3>

      {isLoading ? (
        <div className="text-center py-6 text-[var(--color-text-muted)]">Analyzing...</div>
      ) : !report ? (
        <div className="text-center py-6 text-[var(--color-text-muted)]">No report available</div>
      ) : (
        <>
          {/* Risk Factors */}
          <div>
            <h4 className="text-xs font-semibold text-[var(--color-text-muted)] mb-2 uppercase">
              Risk Factors
            </h4>
            <ul className="space-y-1">
              {report.risk_factors.map((factor, i) => (
                <li key={i} className="text-sm flex gap-2">
                  <span className="text-[var(--color-danger)]">•</span>
                  {factor}
                </li>
              ))}
            </ul>
          </div>

          {/* Top Features */}
          <div>
            <h4 className="text-xs font-semibold text-[var(--color-text-muted)] mb-2 uppercase">
              Top Features
            </h4>
            <div className="space-y-2">
              {report.top_features.slice(0, 5).map((f, i) => (
                <div key={i} className="flex items-center gap-2">
                  <span className="text-xs w-28 truncate text-[var(--color-text-muted)]">
                    {f.feature.replace(/_/g, ' ')}
                  </span>
                  <div className="flex-1 h-1.5 bg-[var(--color-surface-alt)] rounded-full overflow-hidden">
                    <motion.div
                      initial={{ width: 0 }}
                      animate={{ width: `${Math.min(100, f.contribution * 500)}%` }}
                      transition={{ delay: i * 0.1 }}
                      className="h-full rounded-full bg-[var(--color-primary)]"
                    />
                  </div>
                  <span className="text-xs font-mono w-10 text-right">
                    {(f.contribution * 100).toFixed(0)}%
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Signal Breakdown */}
          {report.risk_score_breakdown.length > 0 && (
            <div>
              <h4 className="text-xs font-semibold text-[var(--color-text-muted)] mb-2 uppercase">
                Signal Breakdown
              </h4>
              <div className="space-y-1.5">
                {report.risk_score_breakdown.slice(0, 5).map((sig, i) => (
                  <div key={i} className="text-xs">
                    <div className="flex justify-between mb-0.5">
                      <span className="text-[var(--color-text-muted)]">
                        {sig.signal_name.replace(/_/g, ' ')}
                      </span>
                      <span className="font-mono">
                        {(sig.normalized_score * 100).toFixed(0)}%
                      </span>
                    </div>
                    <div className="h-1 bg-[var(--color-surface-alt)] rounded-full overflow-hidden">
                      <div
                        className="h-full rounded-full bg-gradient-to-r from-[var(--color-primary)] to-[var(--color-danger)]"
                        style={{ width: `${sig.normalized_score * 100}%` }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Confidence */}
          <div className="pt-2 border-t border-[var(--color-border)]">
            <div className="flex justify-between text-sm">
              <span className="text-[var(--color-text-muted)]">Model Confidence</span>
              <span className="font-bold">{(report.model_confidence * 100).toFixed(1)}%</span>
            </div>
          </div>
        </>
      )}
    </motion.div>
  );
}
