apiVersion: v1
kind: Service
metadata:
  name: {{ include "cfi-platform.fullname" . }}-fraud-alert
  labels:
    {{- include "cfi-platform.labels" . | nindent 4 }}
    app: fraud-alert
spec:
  type: {{ .Values.fraudAlert.service.type }}
  ports:
    - port: {{ .Values.fraudAlert.service.port }}
      targetPort: 8003
      protocol: TCP
      name: http
  selector:
    {{- include "cfi-platform.selectorLabels" . | nindent 4 }}
    app: fraud-alert
