apiVersion: v1
kind: Service
metadata:
  name: {{ include "cfi-platform.fullname" . }}-identity-graph
  labels:
    {{- include "cfi-platform.labels" . | nindent 4 }}
    app: identity-graph
spec:
  type: {{ .Values.identityGraph.service.type }}
  ports:
    - port: {{ .Values.identityGraph.service.port }}
      targetPort: 8002
      protocol: TCP
      name: http
  selector:
    {{- include "cfi-platform.selectorLabels" . | nindent 4 }}
    app: identity-graph
