apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cfi-platform.fullname" . }}-secrets
  labels:
    {{- include "cfi-platform.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.postgresql.password | b64enc | quote }}
  JWT_SECRET: {{ .Values.gateway.env.JWT_SECRET | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.gateway.env.OIDC_CLIENT_SECRET | b64enc | quote }}
  VAULT_TOKEN: {{ .Values.gateway.env.VAULT_TOKEN | b64enc | quote }}
